name: Docker

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build image
#        run: docker build . --file Dockerfile --tag georgebronner/golfmapper2:$(date +%s)
        run: docker build . --file Dockerfile --tag georgebronner/golfmapper2:latest
      - name: push image to dockerhub
        run: docker login -u georgebronner -p echo ${{ secrets.DOCKER_HUB_TOKEN }}