name: Build and Push Multi-Arch Image for GolfMapper2

on:
#  push:
#    branches:
#      - main  # Trigger on pushes to the `main` branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: georgebronner/golfmapper2:latest
          platforms: linux/amd64,linux/arm64
