name: Build and Publish Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push images
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u georgebronner --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag georgebronner/golfmapper2:${{ env.TIMESTAMP }} --tag georgebronner/golfmapper2:latest --push .